# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'song-swap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for song-swap
  pod 'Parse'
  pod "Alamofire"
  pod "AlamofireImage"
  pod "SDWebImage"

end
